services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "SuperSafePass.123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

  job-seeker-bot.dashboard:
    image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
    container_name: dashboard
    ports:
      - 18888:18888

  auth-service:
    image: josephrashidmaalouf/auth-service:latest
    container_name: auth-service
    ports:
      - "4001:4001"
    depends_on:
      - sqlserver
      - job-seeker-bot.dashboard
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=AuthDb;User Id=sa;Password=SuperSafePass.123;TrustServerCertificate=True;"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://job-seeker-bot.dashboard:18889"
    volumes:
      - auth_logs:/logs/log
    pull_policy: always


volumes:
  sqlserver_data:
  auth_logs: