name: JobSeekerHelper.AuthService Docker Image CI

on:
  push:
    branches: 
      - "main"
    paths:
      - "AuthService/**"  
  pull_request:
    branches: 
      - "main"
    paths:
      - "AuthService/**"  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

   # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build ./AuthService --file ./AuthService/AuthService/Dockerfile --tag josephrashidmaalouf/auth-service:${{ github.run_id }} --tag josephrashidmaalouf/auth-service:latest

    # Push both the latest and run-id tagged images
    - name: Push Docker images
      run: |
        docker push josephrashidmaalouf/auth-service:latest
        docker push josephrashidmaalouf/auth-service:${{ github.run_id }}
