name: JobSeekerHelper.SearchService Docker Image CI

on:
  push:
    branches:
      - "main"
    paths:
      - "SearchService/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "SearchService/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

        # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./SearchService/SearchService/SearchService.sln

      # Build the solution
      - name: Build solution
        run: dotnet build ./SearchService/SearchService/SearchService.sln --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test ./SearchService/SearchService/SearchService.sln --no-build --configuration Release --logger trx

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build ./SearchService --file ./SearchService/SearchService/Dockerfile --tag josephrashidmaalouf/search-service:${{ github.run_id }} --tag josephrashidmaalouf/search-service:latest

      # Push both the latest and run-id tagged images
      - name: Push Docker images
        run: |
          docker push josephrashidmaalouf/search-service:latest
          docker push josephrashidmaalouf/search-service:${{ github.run_id }}
