name: JobSeekerHelper.UserService Docker Image CI

on:
  push:
    branches: 
      - "main"
    paths:
      - "UserService/**"  
  pull_request:
    branches: 
      - "main"
    paths:
      - "UserService/**"  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

   # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build ./UserService --file ./UserService/UserService/Dockerfile --tag josephrashidmaalouf/user-service:${{ github.run_id }} --tag josephrashidmaalouf/user-service:latest

    # Push both the latest and run-id tagged images
    - name: Push Docker images
      run: |
        docker push josephrashidmaalouf/user-service:latest
        docker push josephrashidmaalouf/user-service:${{ github.run_id }}
